name: 'example oidc'
on:
  push:
    branches:
    - 'main'

jobs:
  run:
    runs-on: 'ubuntu-latest'
    name: 'example to list bucket contents'
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    steps:
    - uses: 'actions/checkout@v3'
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/157097787071/locations/global/workloadIdentityPools/core/attribute.repository/fardarter/gcp-core-infra'
        service_account: 'core-infra@tidy-rainfall-367615.iam.gserviceaccount.com'
    # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    # Now you can run gcloud commands authenticated as the impersonated service account.
    - id: 'gcloud'
      name: 'gcloud'
      run: |-
        gcloud storage ls
      

